/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.Date;

/**
 *
 * @author FALCON DUBAI
 */
import controller.Controller;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Register_Aircraft extends javax.swing.JFrame {

    /**
     * Creates new form Register_Aircraft
     */
    Controller cn;

    public Register_Aircraft() {
        initComponents();
        getRootPane().setDefaultButton(Add);
        
        ownership.add(owned);
        ownership.add(leased);

        cn = new Controller();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int confirm = JOptionPane.showConfirmDialog(
                        Register_Aircraft.this,
                        "Are you sure you want to go back to the Dashboard?",
                        "Return to Dashboard",
                        JOptionPane.YES_NO_OPTION
                );

                if (confirm == JOptionPane.YES_OPTION) {
                    dispose(); // close this window
                    new Admin().setVisible(true); // open dashboard
                }
            }

        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        ownership = new javax.swing.ButtonGroup();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        le = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        modelCombo = new javax.swing.JComboBox<>();
        statCombo = new javax.swing.JComboBox<>();
        EngCombo = new javax.swing.JComboBox<>();
        manfCombo = new javax.swing.JComboBox<>();
        mLease = new javax.swing.JTextField();
        sCapacity = new javax.swing.JTextField();
        bCount = new javax.swing.JSpinner();
        eCount = new javax.swing.JSpinner();
        engCount = new javax.swing.JSpinner();
        fcCount = new javax.swing.JSpinner();
        owned = new javax.swing.JRadioButton();
        leased = new javax.swing.JRadioButton();
        leaseDate = new com.toedter.calendar.JDateChooser();
        reg = new javax.swing.JTextField();
        pPrice = new javax.swing.JTextField();
        fuelT = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextField3.setText("jTextField1");

        jTextField5.setText("jTextField1");

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Airline Management System-Add New Aircraft");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Registration");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Manufacture");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Model");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Seat Capacity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Current Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("----------------------------------------Seat Configuration----------------------------------");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("First Class");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Business");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Seats");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Economy");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Seats");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Seats");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("-------------------------------------------Engine Specifications---------------------------------");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Engine type");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Engine count");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Fuel capacity");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("-----------------------------------------Finincial Information------------------------------------");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("OwnerShip Type");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        le.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        le.setForeground(new java.awt.Color(0, 0, 0));
        le.setText("Lease Expiry");
        getContentPane().add(le, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Purchase price");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Monthly Lease");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        modelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A320", "A350-900", "737-800", "787-9", "E190", "RJ-900", "72-600", "777-300ER", "A380-800", "747-8" }));
        getContentPane().add(modelCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 119, -1));

        statCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Maintenance", "Overhaul", "Storage", "Leased Out", "Leased In", "Sold/Retired", "Test Flight", "Ground Damage", "Ferry Flight", "Pending Delivery", "Emergency Use" }));
        statCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statComboActionPerformed(evt);
            }
        });
        getContentPane().add(statCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 119, -1));

        EngCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turbofan", "Turbojet", "Turboprop", "Turboshaft", "Piston", "Electric", "Hybrid-Electric", "Ramjet", "Scramjet", "Propfan (Unducted Fan)" }));
        getContentPane().add(EngCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 119, -1));

        manfCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Airbus", "Boeing\t", "Embraer\t", "Bombardier\t", "ATR\t", " " }));
        getContentPane().add(manfCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 119, -1));
        getContentPane().add(mLease, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 119, -1));
        getContentPane().add(sCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 119, -1));

        bCount.setModel(new javax.swing.SpinnerNumberModel(0, null, 300, 1));
        getContentPane().add(bCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        eCount.setModel(new javax.swing.SpinnerNumberModel(0, null, 300, 1));
        getContentPane().add(eCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));
        getContentPane().add(engCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        fcCount.setModel(new javax.swing.SpinnerNumberModel(0, null, 300, 2));
        getContentPane().add(fcCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 70, -1));

        owned.setText("Owned");
        owned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownedActionPerformed(evt);
            }
        });
        getContentPane().add(owned, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        leased.setText("Leased");
        leased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leasedActionPerformed(evt);
            }
        });
        getContentPane().add(leased, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));
        getContentPane().add(leaseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 170, -1));
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 119, -1));
        getContentPane().add(pPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 119, -1));
        getContentPane().add(fuelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 110, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Liters");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        Add.setText("Add Aircraft");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        jButton1.setText("Reset Forms");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statComboActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        int id = cn.generateUniqueEmployeeId();
        String registration = reg.getText().trim();
        String manufacture = manfCombo.getSelectedItem().toString();
        String status = statCombo.getSelectedItem().toString();
        String model = modelCombo.getSelectedItem().toString();
        String capacityStr = sCapacity.getText().trim();
        String fuelStr = fuelT.getText().trim();
        String priceStr = pPrice.getText().trim();
        String leaseStr = mLease.getText().trim();
        Date leaseEx = leaseDate.getDate();
        boolean ownedSelected = owned.isSelected();
        boolean leasedSelected = leased.isSelected();

// ✅ Basic field validation
        if (registration.isEmpty() || capacityStr.isEmpty() || fuelStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all required fields (registration, capacity, fuel).", "Missing Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!ownedSelected && !leasedSelected) {
            JOptionPane.showMessageDialog(null, "Please select either Owned or Leased.", "Ownership Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int capacity = Integer.parseInt(capacityStr);
        int fuel = Integer.parseInt(fuelStr);
        int firstclass = Integer.parseInt(fcCount.getValue().toString());
        int businessClass = Integer.parseInt(bCount.getValue().toString());
        int economyClass = Integer.parseInt(eCount.getValue().toString());
        String engineType = EngCombo.getSelectedItem().toString();
        int engineCount = Integer.parseInt(engCount.getValue().toString());
        String ownership = "";
        double monthlyLease = 0.0;
        int price = 0;

        if (ownedSelected) {
            ownership = "Owned";

            if (priceStr.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a price for owned aircraft.", "Missing Price", JOptionPane.WARNING_MESSAGE);
                return;
            }

            price = Integer.parseInt(priceStr);
            leaseEx = null;
            monthlyLease = 0.0;

        } else if (leasedSelected) {
            ownership = "Leased";

            if (leaseStr.isEmpty() || leaseEx == null) {
                JOptionPane.showMessageDialog(null, "Please enter monthly lease and lease expiration date for leased aircraft.", "Missing Lease Info", JOptionPane.WARNING_MESSAGE);
                return;
            }

            monthlyLease = Double.parseDouble(leaseStr);
            price = 0;
        }

//  Confirm save with aircraft summary
        String summary = "Are you sure you want to save this aircraft?\n\n"
                + "Registration: " + registration + "\n"
                + "Manufacturer: " + manufacture + "\n"
                + "Model: " + model + "\n"
                + "Status: " + status + "\n"
                + "Ownership: " + ownership + "\n"
                + (ownership.equals("Owned") ? "Price: $" + price : "Monthly Lease: $" + monthlyLease + "\nLease Expires: " + leaseEx) + "\n"
                + "Capacity: " + capacity + "\n"
                + "First Class: " + firstclass + " | Business: " + businessClass + " | Economy: " + economyClass + "\n"
                + "Engine Type: " + engineType + " | Engine Count: " + engineCount + "\n"
                + "Fuel Capacity: " + fuel + " liters";

        int confirm = JOptionPane.showConfirmDialog(null, summary, "Confirm New Aircraft", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            cn.addAircraftFromGUI(id, registration, manufacture, model, capacity, status, ownership, leaseEx, price, monthlyLease, firstclass, businessClass, economyClass, engineType, engineCount, fuel);

            JOptionPane.showMessageDialog(null, "Aircraft saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            //reset the fields
            reg.setText("");
            manfCombo.setSelectedIndex(0); // resets to first item
            statCombo.setSelectedIndex(0);
            modelCombo.setSelectedIndex(0);
            sCapacity.setText("");
            fcCount.setValue(0);
            bCount.setValue(0);
            eCount.setValue(0);
            EngCombo.setSelectedIndex(0);
            engCount.setValue(0);
            fuelT.setText("");
            pPrice.setText("");
            // mLease.setText(""); // uncomment if Monthly Lease text field is used
            owned.setSelected(false);
            leased.setSelected(false);
            leaseDate.setDate(null); // clears the date chooser

        }

    }//GEN-LAST:event_AddActionPerformed

    private void ownedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownedActionPerformed
        mLease.setVisible(false);
        leaseDate.setVisible(false);
        le.setVisible(false);
        jLabel25.setVisible(false);
        pPrice.setVisible(true);
        jLabel24.setVisible(true);

    }//GEN-LAST:event_ownedActionPerformed

    private void leasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leasedActionPerformed
        pPrice.setVisible(false);
        jLabel24.setVisible(false);
        leaseDate.setVisible(true);
        le.setVisible(true);
        jLabel25.setVisible(true);
        mLease.setVisible(true);

    }//GEN-LAST:event_leasedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reg.setText("");
        manfCombo.setSelectedIndex(0); // resets to first item
        statCombo.setSelectedIndex(0);
        modelCombo.setSelectedIndex(0);
        sCapacity.setText("");
        fcCount.setValue(0);
        bCount.setValue(0);
        eCount.setValue(0);
        EngCombo.setSelectedIndex(0);
        engCount.setValue(0);
        fuelT.setText("");
        pPrice.setText("");
        // mLease.setText(""); // uncomment if Monthly Lease text field is used
        owned.setSelected(false);
        leased.setSelected(false);
        leaseDate.setDate(null); // clears the date chooser
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Aircraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Aircraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Aircraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Aircraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Aircraft().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JComboBox<String> EngCombo;
    private javax.swing.JSpinner bCount;
    private javax.swing.JSpinner eCount;
    private javax.swing.JSpinner engCount;
    private javax.swing.JSpinner fcCount;
    private javax.swing.JTextField fuelT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel le;
    private com.toedter.calendar.JDateChooser leaseDate;
    private javax.swing.JRadioButton leased;
    private javax.swing.JTextField mLease;
    private javax.swing.JComboBox<String> manfCombo;
    private javax.swing.JComboBox<String> modelCombo;
    private javax.swing.JRadioButton owned;
    private javax.swing.ButtonGroup ownership;
    private javax.swing.JTextField pPrice;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField sCapacity;
    private javax.swing.JComboBox<String> statCombo;
    // End of variables declaration//GEN-END:variables
}
